package com.zhs.mytime.filemanage.model;

import java.util.Date;

import com.zhs.mytime.filemanage.comm.FileUtil;

public class ResourceMetadata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.id
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.regdate
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private Date regdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.regname
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String regname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.regcode
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String regcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.filepath
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.filesize
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private Double filesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.videoaudio_posterpath
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String videoaudioPosterpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.filetype
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private Byte filetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.videoaudio_duration
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private Double videoaudioDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.width
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private Double width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.height
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.longitude
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.latitude
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.location_msg
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String locationMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.filename
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.year_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String yearStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.month_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String monthStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.day_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String dayStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.slave_postfix
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String slavePostfix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.weekday_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String weekdayStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_meta_data.clientinfo
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    private String clientinfo;
    
    
    private String  weather;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.id
     *
     * @return the value of resource_meta_data.id
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.id
     *
     * @param id the value for resource_meta_data.id
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.regdate
     *
     * @return the value of resource_meta_data.regdate
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.regdate
     *
     * @param regdate the value for resource_meta_data.regdate
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.regname
     *
     * @return the value of resource_meta_data.regname
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getRegname() {
        return regname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.regname
     *
     * @param regname the value for resource_meta_data.regname
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setRegname(String regname) {
        this.regname = regname == null ? null : regname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.regcode
     *
     * @return the value of resource_meta_data.regcode
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getRegcode() {
        return regcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.regcode
     *
     * @param regcode the value for resource_meta_data.regcode
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setRegcode(String regcode) {
        this.regcode = regcode == null ? null : regcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.filepath
     *
     * @return the value of resource_meta_data.filepath
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.filepath
     *
     * @param filepath the value for resource_meta_data.filepath
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.filesize
     *
     * @return the value of resource_meta_data.filesize
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public Double getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.filesize
     *
     * @param filesize the value for resource_meta_data.filesize
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setFilesize(Double filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.videoaudio_posterpath
     *
     * @return the value of resource_meta_data.videoaudio_posterpath
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getVideoaudioPosterpath() {
        return videoaudioPosterpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.videoaudio_posterpath
     *
     * @param videoaudioPosterpath the value for resource_meta_data.videoaudio_posterpath
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setVideoaudioPosterpath(String videoaudioPosterpath) {
        this.videoaudioPosterpath = videoaudioPosterpath == null ? null : videoaudioPosterpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.filetype
     *
     * @return the value of resource_meta_data.filetype
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public Byte getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.filetype
     *
     * @param filetype the value for resource_meta_data.filetype
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setFiletype(Byte filetype) {
        this.filetype = filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.videoaudio_duration
     *
     * @return the value of resource_meta_data.videoaudio_duration
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public Double getVideoaudioDuration() {
        return videoaudioDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.videoaudio_duration
     *
     * @param videoaudioDuration the value for resource_meta_data.videoaudio_duration
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setVideoaudioDuration(Double videoaudioDuration) {
        this.videoaudioDuration = videoaudioDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.width
     *
     * @return the value of resource_meta_data.width
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public Double getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.width
     *
     * @param width the value for resource_meta_data.width
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setWidth(Double width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.height
     *
     * @return the value of resource_meta_data.height
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.height
     *
     * @param height the value for resource_meta_data.height
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.longitude
     *
     * @return the value of resource_meta_data.longitude
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.longitude
     *
     * @param longitude the value for resource_meta_data.longitude
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.latitude
     *
     * @return the value of resource_meta_data.latitude
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.latitude
     *
     * @param latitude the value for resource_meta_data.latitude
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.location_msg
     *
     * @return the value of resource_meta_data.location_msg
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getLocationMsg() {
        return locationMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.location_msg
     *
     * @param locationMsg the value for resource_meta_data.location_msg
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setLocationMsg(String locationMsg) {
        this.locationMsg = locationMsg == null ? null : locationMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.filename
     *
     * @return the value of resource_meta_data.filename
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.filename
     *
     * @param filename the value for resource_meta_data.filename
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.year_str
     *
     * @return the value of resource_meta_data.year_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getYearStr() {
        return yearStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.year_str
     *
     * @param yearStr the value for resource_meta_data.year_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setYearStr(String yearStr) {
        this.yearStr = yearStr == null ? null : yearStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.month_str
     *
     * @return the value of resource_meta_data.month_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getMonthStr() {
        return monthStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.month_str
     *
     * @param monthStr the value for resource_meta_data.month_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setMonthStr(String monthStr) {
        this.monthStr = monthStr == null ? null : monthStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.day_str
     *
     * @return the value of resource_meta_data.day_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getDayStr() {
        return dayStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.day_str
     *
     * @param dayStr the value for resource_meta_data.day_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setDayStr(String dayStr) {
        this.dayStr = dayStr == null ? null : dayStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.slave_postfix
     *
     * @return the value of resource_meta_data.slave_postfix
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getSlavePostfix() {
        return slavePostfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.slave_postfix
     *
     * @param slavePostfix the value for resource_meta_data.slave_postfix
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setSlavePostfix(String slavePostfix) {
        this.slavePostfix = slavePostfix == null ? null : slavePostfix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.weekday_str
     *
     * @return the value of resource_meta_data.weekday_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getWeekdayStr() {
        return weekdayStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.weekday_str
     *
     * @param weekdayStr the value for resource_meta_data.weekday_str
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setWeekdayStr(String weekdayStr) {
        this.weekdayStr = weekdayStr == null ? null : weekdayStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_meta_data.clientinfo
     *
     * @return the value of resource_meta_data.clientinfo
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public String getClientinfo() {
        return clientinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_meta_data.clientinfo
     *
     * @param clientinfo the value for resource_meta_data.clientinfo
     *
     * @mbggenerated Sat Dec 23 23:42:08 CST 2017
     */
    public void setClientinfo(String clientinfo) {
        this.clientinfo = clientinfo == null ? null : clientinfo.trim();
    }
    
    public String getWeather() {
		return weather;
	}

	public void setWeather(String weather) {
		this.weather = weather;
	}

	public final static byte UNKNOW = (byte) 0;//未知
    public final static byte PIC = (byte) 1;//图片
    public final static byte AUDIO = (byte) 2;//音频
    public final static byte VIDEO = (byte) 3;//视频
    
    //根据文件名返回文件类别
    public static byte getFileType(String fileName){
    	String fileExt = FileUtil.getFileExt(fileName);
    	if("jpg".equalsIgnoreCase(fileExt)||"jpeg".equalsIgnoreCase(fileExt)||"png".equalsIgnoreCase(fileExt)||"gif".equalsIgnoreCase(fileExt)||"icon".equalsIgnoreCase(fileExt)||"bmp".equalsIgnoreCase(fileExt)){
    		return PIC;
    	}else if("silk".equalsIgnoreCase(fileExt)||"wav".equalsIgnoreCase(fileExt)||"mp3".equalsIgnoreCase(fileExt)||"aac".equalsIgnoreCase(fileExt)||"mid".equalsIgnoreCase(fileExt)||"OGG".equalsIgnoreCase(fileExt)){ 
    		return AUDIO;
    	}else if("mp4".equalsIgnoreCase(fileExt)||"avi".equalsIgnoreCase(fileExt)||"rm".equalsIgnoreCase(fileExt)||"wmv".equalsIgnoreCase(fileExt)){
    		return VIDEO;
    	}else{
    		return UNKNOW;
    	}
    }
    
}